### ISSUE TITLE
mysql配置信息完全正确也会导致mysql测试连接失败的问题

### ISSUE THREAD

**Issue by Suntz246** [nnn149/DofLauncher#1]
<HTML>
<head>
这是来自AppDb.cs的49行打debug断点得到的信息</head>

<body>

  | 名称 | 值 | 类型
-- | -- | -- | --
  | password | "uu5!^%jg" | string
  | port | "3306" | string
  | server | "192.168.200.131" | string
  | username | "game" | string

<HTML>
<head>异常捕获信息</head>
<body>

  | 名称 | 值 | 类型
-- | -- | -- | --
  | Message | "'MySQL Server is requesting the insecure pre-4.1 auth mechanism (mysql_old_password). The user password must be upgraded; see https://dev.mysql.com/doc/refman/5.7/en/account-upgrades.html." | string

</body>
</HTML>

>异常原因在于服务器端的密码管理协议陈旧，使用的是旧有的用户密码格式存储；但是客户端升级之后采用了新的密码格式。mysql5.6版本遇到这种不一致的情况就会拒绝连接。

>解决方法：添加连接驱动连接mysql参数secure_auth=off

我c#用的很少，因为你连接数据的信息好像是字符串拼接的我不之道在那里设置mysql驱动的属性，求解惑！
同时我也想制作一下登陆器，如果作者有空可以留个**联系方式**交流一下，我主javaWeb全栈

**Comment by nnn149** [comment]
扣扣:1041836312

**Comment by nnn149** [comment]
你可以在AppDb.cs的第18行
` ConnectionString = "server=" + config.MysqlIP + ";port=" + config.MysqlPort + ";User ID=" + config.MysqlAcc + ";password=" + config.MysqlPwd + ";Database=";`
拼接上`secure_auth=off`
